### ISSUE TITLE
Implement framerate cap

### ISSUE THREAD

**Issue by j-helland** [j-helland/opinion-dynamics#14]
By not capping the framerate, deltaTime can become zero-valued on machines that have been eating a lot protein powder, which will result in all sorts of rendering and physics bugs down the line.

FPS cap should be configurable in our JSON config(s).

Eventually, this should be a user-configurable option within some kind of menu-system.

**Comment by jllusty** [comment]
Framerate is now capped at 60 FPS by measuring the time elapsed between the start and end of the main game loop using glfwGetTime() and telling the main thread to wait for start + 1/60 - finish seconds using std::this_thread::sleep_for().
