### ISSUE TITLE
Animate edges during opinion dynamics steps

### ISSUE THREAD

**Issue by j-helland** [j-helland/opinion-dynamics#4]
We want to make the visualization of opinion dynamics models on our graphs more interpretable by animating an edge between two nodes to show the propagation of one node's opinion to the other.

This animation should start at the node with the dominant opinion and travel towards the node with the subsumed opinion, progressively updating the color.

**Comment by jllusty** [comment]
I've implemented the updates to propagate from the source node to the node assimilating source node's opinion, with the color of the source node's opinion. After the "pulse" reaches the target node, the target node will change it's color to reflect this.
